export const VENDOR_OPERATING_COUNTRIES = [
  { label: "Atlanta - Barrow County", id: "Atlanta - Barrow County" },
  { label: "Atlanta - Bartow County", id: "Atlanta - Bartow County" },
  { label: "Atlanta - Butts County", id: "Atlanta - Butts County" },
  { label: "Atlanta - Carroll County", id: "Atlanta - Carroll County" },
  { label: "Atlanta - Cherokee County", id: "Atlanta - Cherokee County" },
  { label: "Atlanta - Clayton County", id: "Atlanta - Clayton County" },
  { label: "Atlanta - Cobb County", id: "Atlanta - Cobb County" },
  { label: "Atlanta - Coweta County", id: "Atlanta - Coweta County" },
  { label: "Atlanta - Dawson County", id: "Atlanta - Dawson County" },
  { label: "Atlanta - DeKalb County", id: "Atlanta - DeKalb County" },
  { label: "Atlanta - Douglas County", id: "Atlanta - Douglas County" },
  { label: "Atlanta - Fayette County", id: "Atlanta - Fayette County" },
  { label: "Atlanta - Floyd County", id: "Atlanta - Floyd County" },
  { label: "Atlanta - Forsyth County", id: "Atlanta - Forsyth County" },
  { label: "Atlanta - Fulton County", id: "Atlanta - Fulton County" },
  { label: "Atlanta - Gordon County", id: "Atlanta - Gordon County" },
  { label: "Atlanta - Gwinnett County", id: "Atlanta - Gwinnett County" },
  { label: "Atlanta - Hall County", id: "Atlanta - Hall County" },
  { label: "Atlanta - Haralson County", id: "Atlanta - Haralson County" },
  { label: "Atlanta - Heard County", id: "Atlanta - Heard County" },
  { label: "Atlanta - Henry County", id: "Atlanta - Henry County" },
  { label: "Atlanta - Jackson County", id: "Atlanta - Jackson County" },
  { label: "Atlanta - Jasper County", id: "Atlanta - Jasper County" },
  { label: "Atlanta - Lamar County", id: "Atlanta - Lamar County" },
  { label: "Atlanta - Meriwether County", id: "Atlanta - Meriwether County" },
  { label: "Atlanta - Morgan County", id: "Atlanta - Morgan County" },
  { label: "Atlanta - Newton County", id: "Atlanta - Newton County" },
  { label: "Atlanta - Paulding County", id: "Atlanta - Paulding County" },
  { label: "Atlanta - Pickens County", id: "Atlanta - Pickens County" },
  { label: "Atlanta - Pike County", id: "Atlanta - Pike County" },
  { label: "Atlanta - Polk County", id: "Atlanta - Polk County" },
  { label: "Atlanta - Rockdale County", id: "Atlanta - Rockdale County" },
  { label: "Atlanta - Spalding County", id: "Atlanta - Spalding County" },
  { label: "Atlanta - Walton County", id: "Atlanta - Walton County" },
  { label: "Cincinnati - Brown County", id: "Cincinnati - Brown County" },
  { label: "Cincinnati - Butler County", id: "Cincinnati - Butler County" },
  { label: "Cincinnati - Clermont County", id: "Cincinnati - Clermont County" },
  { label: "Cincinnati - Clinton County", id: "Cincinnati - Clinton County" },
  { label: "Cincinnati - Hamilton County", id: "Cincinnati - Hamilton County" },
  { label: "Cincinnati - Warren County", id: "Cincinnati - Warren County" },
  { label: "Cleveland - Ashland County", id: "Cleveland - Ashland County" },
  { label: "Cleveland - Ashtabula County", id: "Cleveland - Ashtabula County" },
  { label: "Cleveland - Carroll County", id: "Cleveland - Carroll County" },
  {
    label: "Cleveland - Columbiana County",
    id: "Cleveland - Columbiana County",
  },
  { label: "Cleveland - Cuyahoga County", id: "Cleveland - Cuyahoga County" },
  { label: "Cleveland - Geauga County", id: "Cleveland - Geauga County" },
  { label: "Cleveland - Lake County", id: "Cleveland - Lake County" },
  { label: "Cleveland - Lorain County", id: "Cleveland - Lorain County" },
  { label: "Cleveland - Mahoning County", id: "Cleveland - Mahoning County" },
  { label: "Cleveland - Medina County", id: "Cleveland - Medina County" },
  { label: "Cleveland - Portage County", id: "Cleveland - Portage County" },
  { label: "Cleveland - Richland County", id: "Cleveland - Richland County" },
  { label: "Cleveland - Stark County", id: "Cleveland - Stark County" },
  { label: "Cleveland - Summit County", id: "Cleveland - Summit County" },
  { label: "Cleveland - Trumbull County", id: "Cleveland - Trumbull County" },
  { label: "Cleveland - Wayne County", id: "Cleveland - Wayne County" },
  {
    label: "Dallas-Fort Worth - Collin County",
    id: "Dallas-Fort Worth - Collin County",
  },
  {
    label: "Dallas-Fort Worth - Dallas County",
    id: "Dallas-Fort Worth - Dallas County",
  },
  {
    label: "Dallas-Fort Worth - Denton County",
    id: "Dallas-Fort Worth - Denton County",
  },
  {
    label: "Dallas-Fort Worth - Ellis County",
    id: "Dallas-Fort Worth - Ellis County",
  },
  {
    label: "Dallas-Fort Worth - Hood County",
    id: "Dallas-Fort Worth - Hood County",
  },
  {
    label: "Dallas-Fort Worth - Hunt County",
    id: "Dallas-Fort Worth - Hunt County",
  },
  {
    label: "Dallas-Fort Worth - Johnson County",
    id: "Dallas-Fort Worth - Johnson County",
  },
  {
    label: "Dallas-Fort Worth - Kaufman County",
    id: "Dallas-Fort Worth - Kaufman County",
  },
  {
    label: "Dallas-Fort Worth - Parker County",
    id: "Dallas-Fort Worth - Parker County",
  },
  {
    label: "Dallas-Fort Worth - Rockwall County",
    id: "Dallas-Fort Worth - Rockwall County",
  },
  {
    label: "Dallas-Fort Worth - Tarrant County",
    id: "Dallas-Fort Worth - Tarrant County",
  },
  {
    label: "Dallas-Fort Worth - Wise County",
    id: "Dallas-Fort Worth - Wise County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Adams County",
    id: "Denver/Colorado Springs/Northern CO - Adams County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Arapahoe County",
    id: "Denver/Colorado Springs/Northern CO - Arapahoe County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Boulder County",
    id: "Denver/Colorado Springs/Northern CO - Boulder County",
  },
  {
    label:
      "Denver/Colorado Springs/Northern CO - City and County of Broomfield",
    id: "Denver/Colorado Springs/Northern CO - City and County of Broomfield",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - City and County of Denver",
    id: "Denver/Colorado Springs/Northern CO - City and County of Denver",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Clear Creek County",
    id: "Denver/Colorado Springs/Northern CO - Clear Creek County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Douglas County",
    id: "Denver/Colorado Springs/Northern CO - Douglas County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - El Paso County",
    id: "Denver/Colorado Springs/Northern CO - El Paso County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Elbert County",
    id: "Denver/Colorado Springs/Northern CO - Elbert County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Jefferson County",
    id: "Denver/Colorado Springs/Northern CO - Jefferson County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Larimer County",
    id: "Denver/Colorado Springs/Northern CO - Larimer County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Park County",
    id: "Denver/Colorado Springs/Northern CO - Park County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Teller County",
    id: "Denver/Colorado Springs/Northern CO - Teller County",
  },
  {
    label: "Denver/Colorado Springs/Northern CO - Weld County",
    id: "Denver/Colorado Springs/Northern CO - Weld County",
  },
  {
    label: "Fort Lauderdale/Palm Beach - Broward County",
    id: "Fort Lauderdale/Palm Beach - Broward County",
  },
  {
    label: "Fort Lauderdale/Palm Beach - Martin County",
    id: "Fort Lauderdale/Palm Beach - Martin County",
  },
  {
    label: "Fort Lauderdale/Palm Beach - Palm Beach County",
    id: "Fort Lauderdale/Palm Beach - Palm Beach County",
  },
  {
    label: "Fort Lauderdale/Palm Beach - St. Lucie County",
    id: "Fort Lauderdale/Palm Beach - St. Lucie County",
  },
  { label: "Fort Myers - Lee County", id: "Fort Myers - Lee County" },
  { label: "Houston - Austin County", id: "Houston - Austin County" },
  { label: "Houston - Brazoria County", id: "Houston - Brazoria County" },
  { label: "Houston - Chambers County", id: "Houston - Chambers County" },
  { label: "Houston - Fort Bend County", id: "Houston - Fort Bend County" },
  { label: "Houston - Galveston County", id: "Houston - Galveston County" },
  { label: "Houston - Harris County", id: "Houston - Harris County" },
  { label: "Houston - Liberty County", id: "Houston - Liberty County" },
  { label: "Houston - Montgomery County", id: "Houston - Montgomery County" },
  { label: "Houston - Waller County", id: "Houston - Waller County" },
  { label: "Jacksonville - Baker County", id: "Jacksonville - Baker County" },
  { label: "Jacksonville - Clay County", id: "Jacksonville - Clay County" },
  { label: "Jacksonville - Duval County", id: "Jacksonville - Duval County" },
  { label: "Jacksonville - Putnam County", id: "Jacksonville - Putnam County" },
  {
    label: "Jacksonville - Saint Johns County",
    id: "Jacksonville - Saint Johns County",
  },
  {
    label: "Macon/Warner Robins - Bibb County",
    id: "Macon/Warner Robins - Bibb County",
  },
  {
    label: "Macon/Warner Robins - Crawford County",
    id: "Macon/Warner Robins - Crawford County",
  },
  {
    label: "Macon/Warner Robins - Houston County",
    id: "Macon/Warner Robins - Houston County",
  },
  {
    label: "Macon/Warner Robins - Jones County",
    id: "Macon/Warner Robins - Jones County",
  },
  {
    label: "Macon/Warner Robins - Monroe County",
    id: "Macon/Warner Robins - Monroe County",
  },
  {
    label: "Macon/Warner Robins - Peach County",
    id: "Macon/Warner Robins - Peach County",
  },
  {
    label: "Macon/Warner Robins - Twiggs County",
    id: "Macon/Warner Robins - Twiggs County",
  },
  { label: "Memphis - Chester County", id: "Memphis - Chester County" },
  { label: "Memphis - Crockett County", id: "Memphis - Crockett County" },
  { label: "Memphis - Dyer County", id: "Memphis - Dyer County" },
  { label: "Memphis - Fayette County", id: "Memphis - Fayette County" },
  { label: "Memphis - Gibson County", id: "Memphis - Gibson County" },
  { label: "Memphis - Hardeman County", id: "Memphis - Hardeman County" },
  { label: "Memphis - Haywood County", id: "Memphis - Haywood County" },
  { label: "Memphis - Lake County", id: "Memphis - Lake County" },
  { label: "Memphis - Madison County", id: "Memphis - Madison County" },
  { label: "Memphis - McNairy County", id: "Memphis - McNairy County" },
  { label: "Memphis - Obion County", id: "Memphis - Obion County" },
  { label: "Memphis - Shelby County", id: "Memphis - Shelby County" },
  { label: "Memphis - Tipton County", id: "Memphis - Tipton County" },
  { label: "Memphis - Weakley County", id: "Memphis - Weakley County" },
  { label: "Miami - Miami-Dade County", id: "Miami - Miami-Dade County" },
  { label: "Minneapolis - Anoka County", id: "Minneapolis - Anoka County" },
  { label: "Minneapolis - Carver County", id: "Minneapolis - Carver County" },
  { label: "Minneapolis - Chisago County", id: "Minneapolis - Chisago County" },
  { label: "Minneapolis - Dakota County", id: "Minneapolis - Dakota County" },
  {
    label: "Minneapolis - Hennepin County",
    id: "Minneapolis - Hennepin County",
  },
  { label: "Minneapolis - Isanti County", id: "Minneapolis - Isanti County" },
  {
    label: "Minneapolis - Le Sueur County",
    id: "Minneapolis - Le Sueur County",
  },
  {
    label: "Minneapolis - Mille Lacs County",
    id: "Minneapolis - Mille Lacs County",
  },
  { label: "Minneapolis - Ramsey County", id: "Minneapolis - Ramsey County" },
  { label: "Minneapolis - Scott County", id: "Minneapolis - Scott County" },
  {
    label: "Minneapolis - Sherburne County",
    id: "Minneapolis - Sherburne County",
  },
  { label: "Minneapolis - Sibley County", id: "Minneapolis - Sibley County" },
  {
    label: "Minneapolis - Washington County",
    id: "Minneapolis - Washington County",
  },
  { label: "Minneapolis - Wright County", id: "Minneapolis - Wright County" },
  { label: "Orlando - Lake County", id: "Orlando - Lake County" },
  { label: "Orlando - Orange County", id: "Orlando - Orange County" },
  { label: "Orlando - Osceola County", id: "Orlando - Osceola County" },
  { label: "Orlando - Seminole County", id: "Orlando - Seminole County" },
  { label: "Orlando - Sumter County", id: "Orlando - Sumter County" },
  { label: "Orlando - Volusia County", id: "Orlando - Volusia County" },
  { label: "Phoenix - Maricopa County", id: "Phoenix - Maricopa County" },
  { label: "Phoenix - Pinal County", id: "Phoenix - Pinal County" },
  { label: "Pueblo - Pueblo County", id: "Pueblo - Pueblo County" },
  {
    label: "San Antonio - Atascosa County",
    id: "San Antonio - Atascosa County",
  },
  { label: "San Antonio - Bandera County", id: "San Antonio - Bandera County" },
  { label: "San Antonio - Bexar County", id: "San Antonio - Bexar County" },
  { label: "San Antonio - Comal County", id: "San Antonio - Comal County" },
  {
    label: "San Antonio - Guadalupe County",
    id: "San Antonio - Guadalupe County",
  },
  { label: "San Antonio - Kendall County", id: "San Antonio - Kendall County" },
  { label: "San Antonio - Medina County", id: "San Antonio - Medina County" },
  { label: "San Antonio - Wilson County", id: "San Antonio - Wilson County" },
  {
    label: "St. Louis - City of St. Louis",
    id: "St. Louis - City of St. Louis",
  },
  { label: "St. Louis - Franklin County", id: "St. Louis - Franklin County" },
  { label: "St. Louis - Jefferson County", id: "St. Louis - Jefferson County" },
  { label: "St. Louis - Lincoln County", id: "St. Louis - Lincoln County" },
  {
    label: "St. Louis - St. Charles County",
    id: "St. Louis - St. Charles County",
  },
  { label: "St. Louis - St. Louis County", id: "St. Louis - St. Louis County" },
  { label: "St. Louis - Warren County", id: "St. Louis - Warren County" },
  { label: "Tampa - Citrus County", id: "Tampa - Citrus County" },
  { label: "Tampa - Hernando County", id: "Tampa - Hernando County" },
  { label: "Tampa - Hillsborough County", id: "Tampa - Hillsborough County" },
  { label: "Tampa - Pasco County", id: "Tampa - Pasco County" },
  { label: "Tampa - Pinellas County", id: "Tampa - Pinellas County" },
  { label: "Tampa - Polk County", id: "Tampa - Polk County" },
  { label: "Tampa - Sarasota County", id: "Tampa - Sarasota County" },
];

export const VENDOR_SERVICES = [
  {
    label: "Appliance Repair - Dishwasher",
    id: "Appliance Repair - Dishwasher",
  },
  {
    label: "Appliance Repair - Garbage disposal",
    id: "Appliance Repair - Garbage disposal",
  },
  { label: "Appliance Repair - Microwave", id: "Appliance Repair - Microwave" },
  {
    label: "Appliance Repair - Oven and Range Maintenance",
    id: "Appliance Repair - Oven and Range Maintenance",
  },
  {
    label: "Appliance Repair - Refrigerator",
    id: "Appliance Repair - Refrigerator",
  },
  {
    label: "Appliance Repair - Washer and Dryer Repair",
    id: "Appliance Repair - Washer and Dryer Repair",
  },
  {
    label: "Appliance Repair - Water Softener (wells)",
    id: "Appliance Repair - Water Softener (wells)",
  },
  { label: "Appliances", id: "Appliances" },
  { label: "Asbestos - Licensed", id: "Asbestos - Licensed" },
  { label: "Asbestos - Remediation", id: "Asbestos - Remediation" },
  { label: "Asbestos - Testing", id: "Asbestos - Testing" },
  { label: "Carpentry - Cabinets", id: "Carpentry - Cabinets" },
  { label: "Carpentry - Deck Repairs", id: "Carpentry - Deck Repairs" },
  { label: "Carpentry - Doors", id: "Carpentry - Doors" },
  { label: "Carpentry - Trim/Baseboards", id: "Carpentry - Trim/Baseboards" },
  {
    label: "Cleaning Services - Carpet Cleaning",
    id: "Cleaning Services - Carpet Cleaning",
  },
  {
    label: "Cleaning Services - Construction Clean Up",
    id: "Cleaning Services - Construction Clean Up",
  },
  {
    label: "Cleaning Services - Water Extraction",
    id: "Cleaning Services - Water Extraction",
  },
  {
    label: "Electrical - Licensed Electrician Services",
    id: "Electrical - Licensed Electrician Services",
  },
  {
    label: "Electrical - Lighting Installation/Repair",
    id: "Electrical - Lighting Installation/Repair",
  },
  { label: "Electrical - Panel Upgrades", id: "Electrical - Panel Upgrades" },
  {
    label: "Electrical - Wiring and Rewiring",
    id: "Electrical - Wiring and Rewiring",
  },
  {
    label: "Environmental Testing - Air Quality",
    id: "Environmental Testing - Air Quality",
  },
  { label: "Environmental Testing - Mold", id: "Environmental Testing - Mold" },
  { label: "Fireplaces", id: "Fireplaces" },
  { label: "Fireplaces - Cleaning", id: "Fireplaces - Cleaning" },
  { label: "Fireplaces - Repair", id: "Fireplaces - Repair" },
  { label: "Fireplaces - Sealing", id: "Fireplaces - Sealing" },
  { label: "Flooring", id: "Flooring" },
  { label: "Flooring - Demo", id: "Flooring - Demo" },
  { label: "Flooring - Install", id: "Flooring - Install" },
  { label: "Flooring - Repair", id: "Flooring - Repair" },
  { label: "Flooring - Resurface", id: "Flooring - Resurface" },
  { label: "Flooring - Subflooring", id: "Flooring - Subflooring" },
  {
    label: "Foundation/Structural - Engineering Licensed",
    id: "Foundation/Structural - Engineering Licensed",
  },
  {
    label: "Foundation/Structural - Foundation Repair",
    id: "Foundation/Structural - Foundation Repair",
  },
  {
    label: "Foundation/Structural - Masonry and Concrete Repair",
    id: "Foundation/Structural - Masonry and Concrete Repair",
  },
  {
    label: "Foundation/Structural - Siding Repair",
    id: "Foundation/Structural - Siding Repair",
  },
  {
    label: "Foundation/Structural - Structural Inspections",
    id: "Foundation/Structural - Structural Inspections",
  },
  {
    label: "Foundation/Structural - Waterproofing",
    id: "Foundation/Structural - Waterproofing",
  },
  {
    label: "Garage Repairs - Full Replacement Motor Spring Door",
    id: "Garage Repairs - Full Replacement Motor Spring Door",
  },
  { label: "Garage Repairs - Partial", id: "Garage Repairs - Partial" },
  { label: "Garages", id: "Garages" },
  { label: "HVAC", id: "HVAC" },
  { label: "HVAC - Air Duct Cleaning", id: "HVAC - Air Duct Cleaning" },
  { label: "HVAC - Boiler Systems", id: "HVAC - Boiler Systems" },
  { label: "HVAC - Installation", id: "HVAC - Installation" },
  { label: "HVAC - Licensed", id: "HVAC - Licensed" },
  {
    label: "HVAC - Preventative Maintenance",
    id: "HVAC - Preventative Maintenance",
  },
  { label: "HVAC - Repair", id: "HVAC - Repair" },
  { label: "Landscaping", id: "Landscaping" },
  { label: "Landscaping - Fencing", id: "Landscaping - Fencing" },
  {
    label: "Landscaping - Hardscape Installation",
    id: "Landscaping - Hardscape Installation",
  },
  {
    label: "Landscaping - Irrigation System Maintenance",
    id: "Landscaping - Irrigation System Maintenance",
  },
  { label: "Landscaping - Lawn Care", id: "Landscaping - Lawn Care" },
  {
    label: "Landscaping - Tree and Shrub Care",
    id: "Landscaping - Tree and Shrub Care",
  },
  {
    label: "Landscaping - Tree/Stump Removal",
    id: "Landscaping - Tree/Stump Removal",
  },
  { label: "Lead - Licensed", id: "Lead - Licensed" },
  { label: "Lead - Remediation", id: "Lead - Remediation" },
  { label: "Lead - Testing", id: "Lead - Testing" },
  { label: "Painting", id: "Painting" },
  { label: "Painting - Deck Staining", id: "Painting - Deck Staining" },
  { label: "Painting - Drywall Repair", id: "Painting - Drywall Repair" },
  { label: "Painting - Exterior", id: "Painting - Exterior" },
  { label: "Painting - Interior", id: "Painting - Interior" },
  { label: "Pest Control", id: "Pest Control" },
  { label: "Pest Control - Exclusion", id: "Pest Control - Exclusion" },
  { label: "Pest Control - Extermination", id: "Pest Control - Extermination" },
  { label: "Pest Control - Inspection", id: "Pest Control - Inspection" },
  { label: "Pest Control - Licensed", id: "Pest Control - Licensed" },
  {
    label: "Pest Control - Preventative Pest Management",
    id: "Pest Control - Preventative Pest Management",
  },
  {
    label: "Pest Control - Wildlife Removal",
    id: "Pest Control - Wildlife Removal",
  },
  { label: "Plumbing - Drain Cleaning", id: "Plumbing - Drain Cleaning" },
  { label: "Plumbing - Gas Leak Repair", id: "Plumbing - Gas Leak Repair" },
  { label: "Plumbing - Licensed", id: "Plumbing - Licensed" },
  { label: "Plumbing - Long Scope Camera", id: "Plumbing - Long Scope Camera" },
  { label: "Plumbing - Pipe Replacement", id: "Plumbing - Pipe Replacement" },
  { label: "Plumbing - Repairs", id: "Plumbing - Repairs" },
  {
    label: "Plumbing - Sewer Line Replacement",
    id: "Plumbing - Sewer Line Replacement",
  },
  {
    label: "Plumbing - Water Heater Maintenance",
    id: "Plumbing - Water Heater Maintenance",
  },
  { label: "Pool", id: "Pool" },
  { label: "Pool - Maintenance", id: "Pool - Maintenance" },
  { label: "Pool - Renovations", id: "Pool - Renovations" },
  { label: "Pool - Repairs", id: "Pool - Repairs" },
  { label: "Pool - Safety Measures", id: "Pool - Safety Measures" },
  { label: "Pool - Structural", id: "Pool - Structural" },
  {
    label: "Restoration - Fire remediation",
    id: "Restoration - Fire remediation",
  },
  { label: "Restoration - Licensed", id: "Restoration - Licensed" },
  {
    label: "Restoration - Mold Remediation",
    id: "Restoration - Mold Remediation",
  },
  { label: "Restoration - Testing", id: "Restoration - Testing" },
  {
    label: "Restoration - Water Extraction",
    id: "Restoration - Water Extraction",
  },
  { label: "Roofing", id: "Roofing" },
  { label: "Roofing - Gutter Maintenance", id: "Roofing - Gutter Maintenance" },
  { label: "Roofing - Inspection", id: "Roofing - Inspection" },
  { label: "Roofing - Licensed", id: "Roofing - Licensed" },
  { label: "Roofing - Repair", id: "Roofing - Repair" },
  { label: "Roofing - Replacement", id: "Roofing - Replacement" },
  { label: "Septic/Sewer - Inspection", id: "Septic/Sewer - Inspection" },
  { label: "Septic/Sewer - Licensed", id: "Septic/Sewer - Licensed" },
  { label: "Septic/Sewer - Pump", id: "Septic/Sewer - Pump" },
  { label: "Septic/Sewer - Repair", id: "Septic/Sewer - Repair" },
  { label: "Septic/Sewer - Replace", id: "Septic/Sewer - Replace" },
  { label: "Window - Glass Replacement", id: "Window - Glass Replacement" },
  { label: "Window - Reglazing", id: "Window - Reglazing" },
  { label: "Window - Repair", id: "Window - Repair" },
  { label: "Window - Replace", id: "Window - Replace" },
  { label: "Windows", id: "Windows" },
];

export const API_URL = import.meta.env.VITE_APP_API_URL;
